package ru.tinkoff.edu.java.scrapper.domain.jooq;

import javax.annotation.processing.Generated;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Link;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.User;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.UserLink;

@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    public static final Link LINK = Link.LINK;

    public static final User USER = User.USER;

    public static final UserLink USER_LINK = UserLink.USER_LINK;
}